### PR TITLE
Add Installation Chrome part to README

### PR DESCRIPTION
**Pull request by ycs77**
If there are steps to install **Chrome** in the README, using **Depictr** will be much easier, no need to go to the search for how to install **Chrome**.

After the local test was completed, I pushed the website to **Heroku** and write to README the way it was built.

### CODE REVIEW

**Comment by Juhlinus** [comment]
Hi @ycs77 !

Thanks for the PR.

[Symfony/Panther](https://github.com/symfony/panther/) which Depictr uses under the hood [comes with a chromedriver binary by default](https://github.com/symfony/panther/tree/master/chromedriver-bin), so there's no need to install it on your own.

Are you experiencing any issues with the binary not being found?

**Comment by ycs77** [comment]
I know the chromedriver exists in Symfony/Panther.

The my issue is #3. I use Panther's chromedriver in Depictr, but it does not work. php-webdriver throw "unknown error: cannot find Chrome binary" 😥



It was search until later that know, I need local Chrome browser, but it still does not work after download. The reason is that the major version of the local Chrome browser and chromedriver must be the same. Can work after solving. 😑

**Comment by Juhlinus** [comment]
Is this an issue that persists both on your Windows machine and on Heroku?

**Comment by ycs77** [comment]
## 1. Homestead (virtualbox driver in Windows)

The issue is now solved. after installing the Chrome browser (run `sudo apt-get install chromium-browser` in Homestead) can running Depictr.

## 2. Heroku

The Heroku I find the [heroku-buildpack-chromedriver](https://github.com/heroku/heroku-buildpack-chromedriver), but the README say:

> This buildpack only installs the `chromedriver` binary. To use Selenium with Chrome on Heroku, you'll also need Chrome. We suggest one of these buildpacks:
>
> * [heroku-buildpack-google-chrome](https://github.com/heroku/heroku-buildpack-google-chrome) to run Chrome with the `--headless` flag
> * ...

Then I install the [heroku-buildpack-chromedriver](https://github.com/heroku/heroku-buildpack-chromedriver) and [heroku-buildpack-google-chrome](https://github.com/heroku/heroku-buildpack-google-chrome) both, push code to Heroku, Depictr successfully running! 😎

### Look the Inertia SSR on Heroku

This is an Inertia SPA website with Depictr and top two heroku buildpack on the Heroku:

1. The meta setting in Vue page

ssr-1

2. Check the Laravel website on Heroku is SPA

ssr-2

3. Use FB debugger tool crawling meta in the SPA

ssr-3

---

This PR is written my process of installing install Chrome let me can running Depictr in my Laravel app because the Depictr depends on the chromedriver and Chrome browser. I hope other people use Depictr can be easy, Instead of wasting a lot of time searching on Google. But my mother tongue is not English, there may be errors in the grammar, which can be optimized. 😊

Do you have any thoughts on this?

**Comment by Juhlinus** [comment]
Thanks for your work @ycs77 !

I'll have a look at the documentation you've added and correct your grammar if there are any errors and merge this is the coming days. 😀

**Pull request closed without merging**
